### ISSUE TITLE
mix deps.compile error

### ISSUE THREAD

**Issue by otherNet** [omgnetwork/elixir-omg#1727]
Hi everyone, I'm a newbie on plasma with some knoledge about ethereum. I'm tryng to follow your steps in omg with the final intent  to set up a test omg network on ropsten for my company.
I get stucked during installation: I got an error at mix compile. 

I'm working on Vbox, linux ubuntu 16.04, 
this is the elixir version:
`fra@server1604:~/elixir-omg$ elixir --version
Erlang/OTP 23 [erts-11.0.3] [source] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:1]

Elixir 1.10.2 (compiled with Erlang/OTP 21)`

this the output what I get:

`
fra@server1604:~/elixir-omg$ mix deps.compile
==> omg_utils
Compiling 8 files (.ex)

== Compilation error in file lib/omg_utils/http_rpc/adapter.ex ==
** (CompileError) lib/omg_utils/http_rpc/adapter.ex:30: HTTPoison.Response.__struct__/0 is undefined, cannot expand struct HTTPoison.Response. Make sure the struct name is correct. If the struct name exists and is correct but it still cannot be found, you likely have cyclic module usage in your code
    (stdlib 3.13) lists.erl:1354: :lists.mapfoldl/3
    (stdlib 3.13) lists.erl:1355: :lists.mapfoldl/3
could not compile dependency :omg_utils, "mix compile" failed. You can recompile this dependency with "mix deps.compile omg_utils", update it with "mix deps.update omg_utils" or clean it with "mix deps.clean omg_utils"
`

Hope you can help.

**Comment by unnawut** [comment]
It looks like you're missing `HTTPoison` library. Could you double check that you already ran `mix deps.get`?

Also, could you give a bit more info on which instructions are you following, e.g. a link to the documentation page? So we can double check if any step is missing.

Let us know if you have further questions/details!

**Comment by otherNet** [comment]
Thank you for your answer.

I'm following the intall instruction @: https://github.com/omgnetwork/elixir-omg/blob/master/docs/install.md
I get the error at 3° instruction of build section: mix dep.compile, I already executed mix deps.get.
Now if I launch it again I get the following:

`
fra@server1604:~/elixir-omg$ mix deps.get                                       
Resolving Hex dependencies...
Dependency resolution completed:
Unchanged:
  binary 0.0.5
  briefly 0.3.0
  bunt 0.2.0
  certifi 2.5.2
  connection 1.0.4
  cors_plug 2.0.2
  cowboy 2.8.0
  cowlib 2.9.1
  credo 1.4.0
  db_connection 2.2.2
  decimal 1.8.1
  decorator 1.3.2
  dialyxir 1.0.0
  earmark 1.4.4
  ecto 3.4.4
  ecto_sql 3.4.4
  erlex 0.2.6
  erlexec 1.10.9
  ethereumex 0.6.2
  ex_abi 0.4.0
  ex_doc 0.20.2
  ex_machina 2.4.0
  ex_rlp 0.5.3
  excoveralls 0.12.3
  exth_crypto 0.1.6
  fake_server 2.1.0
  hackney 1.16.0
  httpoison 1.6.2
  idna 6.0.1
  ink 1.1.1
  jason 1.2.1
  keccakf1600_orig 2.0.0
  licensir 0.2.7
  makeup 1.0.2
  makeup_elixir 0.14.1
  merkle_tree 2.0.0
  metrics 1.0.1
  mime 1.3.1
  mimerl 1.2.0
  mix_audit 0.1.4
  msgpax 2.2.4
  nimble_parsec 0.6.0
  optimal 0.3.6
  parse_trans 3.3.0
  phoenix 1.5.4
  phoenix_pubsub 2.0.0
  plug 1.10.3
  plug_cowboy 2.3.0
  plug_crypto 1.1.2
  poison 4.0.1
  poolboy 1.5.2
  postgrex 0.15.4
  propcheck 1.2.0
  proper 1.3.0
  ranch 1.7.1
  rocksdb 1.5.1
  sentry 7.2.4
  spandex 3.0.2
  spandex_datadog 1.0.0
  spandex_ecto 0.6.2
  spandex_phoenix 1.0.3
  ssl_verify_fun 1.1.6
  telemetry 0.4.2
  unicode_util_compat 0.5.0
  vmstats 2.4.0
  yamerl 0.8.0
  yaml_elixir 2.4.0
`
Thanks in advance.

**Comment by otherNet** [comment]
Hi, thank for youe answer !

I'm executing commands in the Build section of: https://github.com/omgnetwork/elixir-omg/blob/master/docs/install.md
I get the error at the third instruction after I already executed  "mix deps.get" command.
If I launch it now I get the following:

fra@server1604:~/elixir-omg$ mix deps.get                                       
Resolving Hex dependencies...
Dependency resolution completed:
Unchanged:
  binary 0.0.5
  briefly 0.3.0
  bunt 0.2.0
  certifi 2.5.2
  connection 1.0.4
  cors_plug 2.0.2
  cowboy 2.8.0
  cowlib 2.9.1
  credo 1.4.0
  db_connection 2.2.2
  decimal 1.8.1
  decorator 1.3.2
  dialyxir 1.0.0
  earmark 1.4.4
  ecto 3.4.4
  ecto_sql 3.4.4
  erlex 0.2.6
  erlexec 1.10.9
  ethereumex 0.6.2
  ex_abi 0.4.0
  ex_doc 0.20.2
  ex_machina 2.4.0
  ex_rlp 0.5.3
  excoveralls 0.12.3
  exth_crypto 0.1.6
  fake_server 2.1.0
  hackney 1.16.0
  httpoison 1.6.2
  idna 6.0.1
  ink 1.1.1
  jason 1.2.1
  keccakf1600_orig 2.0.0
  licensir 0.2.7
  makeup 1.0.2
  makeup_elixir 0.14.1
  merkle_tree 2.0.0
  metrics 1.0.1
  mime 1.3.1
  mimerl 1.2.0
  mix_audit 0.1.4
  msgpax 2.2.4
  nimble_parsec 0.6.0
  optimal 0.3.6
  parse_trans 3.3.0
  phoenix 1.5.4
  phoenix_pubsub 2.0.0
  plug 1.10.3
  plug_cowboy 2.3.0
  plug_crypto 1.1.2
  poison 4.0.1
  poolboy 1.5.2
  postgrex 0.15.4
  propcheck 1.2.0
  proper 1.3.0
  ranch 1.7.1
  rocksdb 1.5.1
  sentry 7.2.4
  spandex 3.0.2
  spandex_datadog 1.0.0
  spandex_ecto 0.6.2
  spandex_phoenix 1.0.3
  ssl_verify_fun 1.1.6
  telemetry 0.4.2
  unicode_util_compat 0.5.0
  vmstats 2.4.0
  yamerl 0.8.0
  yaml_elixir 2.4.0

thanks in advance.

**Comment by InoMurko** [comment]
Don't run `mix deps.compile`, just run `mix compile`.

**Comment by otherNet** [comment]
Ok. Now I got:

fra@server1604:~/elixir-omg$ mix compile
==> erlex
Compiling 1 file (.yrl)
/usr/lib/erlang/lib/parsetools-2.2/include/yeccpre.hrl: no such file or directory
src/parser.yrl: Warning: conflicts: 27 shift/reduce, 0 reduce/reduce
could not compile dependency :erlex, "mix compile" failed. You can recompile this dependency with "mix deps.compile erlex", update it with "mix deps.update erlex" or clean it with "mix deps.clean erlex"

looking around: https://elixirforum.com/t/usr-lib-erlang-lib-parsetools-2-2-include-yeccpre-hrl-no-such-file-or-directory/32386/3

this is my erlang-parsetools situation:

fra@server1604:~/elixir-omg$ apt search parsetools
Ordinamento... done
Ricerca sul testo... done
erlang-parsetools/unknown,now 1:23.0.3-1 amd64 [**installato**]
  strumenti per analisi di Erlang/OTP

Erlang installation again I suppose ...

**Comment by InoMurko** [comment]
I suggest you install erlang and elixir with `asdf`. https://github.com/asdf-vm/asdf

Or, alternatively: 
`sudo apt-get install -y erlang-os-mon erlang-parsetools erlang-tools`

**Comment by otherNet** [comment]
I installed these different libraries beacuse I missed the /include subdirectory in /usr/lib/erlang/lib/parsetools-2.2

      apt-get install erlang-base-hipe  erlang-dev  erlang-eunit
as suggested at : https://github.com/phoenixframework/phoenix/issues/1411
(so probably asdf is a better way)

Now without asdf this is the next step but new different error

fra@server1604:~/elixir-omg$ mix compile
==> erlex
Compiling 1 file (.yrl)
src/parser.yrl: Warning: conflicts: 27 shift/reduce, 0 reduce/reduce
Compiling 1 file (.xrl)
Compiling 2 files (.erl)
Compiling 1 file (.ex)
Generated erlex app
==> optimal
Compiling 5 files (.ex)
Generated optimal app
===> Compiling mimerl
===> Compiling yamerl
/home/fra/elixir-omg/deps/yamerl/include/internal/yamerl_constr.hrl:45: Warning: record unfinished_node has field(s) without type information
/home/fra/elixir-omg/deps/yamerl/include/internal/yamerl_constr.hrl:52: Warning: record node_anchor has field(s) without type information
include/internal/yamerl_constr.hrl:45: Warning: record unfinished_node has field(s) without type information
include/internal/yamerl_constr.hrl:52: Warning: record node_anchor has field(s) without type information

/home/fra/elixir-omg/deps/yamerl/include/internal/yamerl_constr.hrl:45: Warning: record unfinished_node has field(s) without type information
/home/fra/elixir-omg/deps/yamerl/include/internal/yamerl_constr.hrl:52: Warning: record node_anchor has field(s) without type information
include/internal/yamerl_constr.hrl:45: Warning: record unfinished_node has field(s) without type information
include/internal/yamerl_constr.hrl:52: Warning: record node_anchor has field(s) without type information

/home/fra/elixir-omg/deps/yamerl/include/internal/yamerl_constr.hrl:45: Warning: record unfinished_node has field(s) without type information
/home/fra/elixir-omg/deps/yamerl/include/internal/yamerl_constr.hrl:52: Warning: record node_anchor has field(s) without type information
include/internal/yamerl_constr.hrl:45: Warning: record unfinished_node has field(s) without type information
include/internal/yamerl_constr.hrl:52: Warning: record node_anchor has field(s) without type information

/home/fra/elixir-omg/deps/yamerl/include/internal/yamerl_constr.hrl:45: Warning: record unfinished_node has field(s) without type information
/home/fra/elixir-omg/deps/yamerl/include/internal/yamerl_constr.hrl:52: Warning: record node_anchor has field(s) without type information
include/internal/yamerl_constr.hrl:45: Warning: record unfinished_node has field(s) without type information
include/internal/yamerl_constr.hrl:52: Warning: record node_anchor has field(s) without type information

/home/fra/elixir-omg/deps/yamerl/include/internal/yamerl_constr.hrl:45: Warning: record unfinished_node has field(s) without type information
/home/fra/elixir-omg/deps/yamerl/include/internal/yamerl_constr.hrl:52: Warning: record node_anchor has field(s) without type information
include/internal/yamerl_constr.hrl:45: Warning: record unfinished_node has field(s) without type information
include/internal/yamerl_constr.hrl:52: Warning: record node_anchor has field(s) without type information

/home/fra/elixir-omg/deps/yamerl/include/internal/yamerl_constr.hrl:45: Warning: record unfinished_node has field(s) without type information
/home/fra/elixir-omg/deps/yamerl/include/internal/yamerl_constr.hrl:52: Warning: record node_anchor has field(s) without type information
include/internal/yamerl_constr.hrl:45: Warning: record unfinished_node has field(s) without type information
include/internal/yamerl_constr.hrl:52: Warning: record node_anchor has field(s) without type information

/home/fra/elixir-omg/deps/yamerl/include/internal/yamerl_constr.hrl:45: Warning: record unfinished_node has field(s) without type information
/home/fra/elixir-omg/deps/yamerl/include/internal/yamerl_constr.hrl:52: Warning: record node_anchor has field(s) without type information
include/internal/yamerl_constr.hrl:45: Warning: record unfinished_node has field(s) without type information
include/internal/yamerl_constr.hrl:52: Warning: record node_anchor has field(s) without type information

/home/fra/elixir-omg/deps/yamerl/include/internal/yamerl_constr.hrl:45: Warning: record unfinished_node has field(s) without type information
/home/fra/elixir-omg/deps/yamerl/include/internal/yamerl_constr.hrl:52: Warning: record node_anchor has field(s) without type information
include/internal/yamerl_constr.hrl:45: Warning: record unfinished_node has field(s) without type information
include/internal/yamerl_constr.hrl:52: Warning: record node_anchor has field(s) without type information

/home/fra/elixir-omg/deps/yamerl/include/internal/yamerl_constr.hrl:45: Warning: record unfinished_node has field(s) without type information
/home/fra/elixir-omg/deps/yamerl/include/internal/yamerl_constr.hrl:52: Warning: record node_anchor has field(s) without type information
include/internal/yamerl_constr.hrl:45: Warning: record unfinished_node has field(s) without type information
include/internal/yamerl_constr.hrl:52: Warning: record node_anchor has field(s) without type information

/home/fra/elixir-omg/deps/yamerl/include/internal/yamerl_constr.hrl:45: Warning: record unfinished_node has field(s) without type information
/home/fra/elixir-omg/deps/yamerl/include/internal/yamerl_constr.hrl:52: Warning: record node_anchor has field(s) without type information
include/internal/yamerl_constr.hrl:45: Warning: record unfinished_node has field(s) without type information
include/internal/yamerl_constr.hrl:52: Warning: record node_anchor has field(s) without type information

/home/fra/elixir-omg/deps/yamerl/include/internal/yamerl_constr.hrl:45: Warning: record unfinished_node has field(s) without type information
/home/fra/elixir-omg/deps/yamerl/include/internal/yamerl_constr.hrl:52: Warning: record node_anchor has field(s) without type information
include/internal/yamerl_constr.hrl:45: Warning: record unfinished_node has field(s) without type information
include/internal/yamerl_constr.hrl:52: Warning: record node_anchor has field(s) without type information

/home/fra/elixir-omg/deps/yamerl/include/internal/yamerl_constr.hrl:45: Warning: record unfinished_node has field(s) without type information
/home/fra/elixir-omg/deps/yamerl/include/internal/yamerl_constr.hrl:52: Warning: record node_anchor has field(s) without type information
include/internal/yamerl_constr.hrl:45: Warning: record unfinished_node has field(s) without type information
include/internal/yamerl_constr.hrl:52: Warning: record node_anchor has field(s) without type information

/home/fra/elixir-omg/deps/yamerl/include/internal/yamerl_constr.hrl:45: Warning: record unfinished_node has field(s) without type information
/home/fra/elixir-omg/deps/yamerl/include/internal/yamerl_constr.hrl:52: Warning: record node_anchor has field(s) without type information
include/internal/yamerl_constr.hrl:45: Warning: record unfinished_node has field(s) without type information
include/internal/yamerl_constr.hrl:52: Warning: record node_anchor has field(s) without type information

/home/fra/elixir-omg/deps/yamerl/include/internal/yamerl_constr.hrl:45: Warning: record unfinished_node has field(s) without type information
/home/fra/elixir-omg/deps/yamerl/include/internal/yamerl_constr.hrl:52: Warning: record node_anchor has field(s) without type information
include/internal/yamerl_constr.hrl:45: Warning: record unfinished_node has field(s) without type information
include/internal/yamerl_constr.hrl:52: Warning: record node_anchor has field(s) without type information

/home/fra/elixir-omg/deps/yamerl/include/internal/yamerl_constr.hrl:45: Warning: record unfinished_node has field(s) without type information
/home/fra/elixir-omg/deps/yamerl/include/internal/yamerl_constr.hrl:52: Warning: record node_anchor has field(s) without type information
include/internal/yamerl_constr.hrl:45: Warning: record unfinished_node has field(s) without type information
include/internal/yamerl_constr.hrl:52: Warning: record node_anchor has field(s) without type information

/home/fra/elixir-omg/deps/yamerl/include/internal/yamerl_constr.hrl:45: Warning: record unfinished_node has field(s) without type information
/home/fra/elixir-omg/deps/yamerl/include/internal/yamerl_constr.hrl:52: Warning: record node_anchor has field(s) without type information
include/internal/yamerl_constr.hrl:45: Warning: record unfinished_node has field(s) without type information
include/internal/yamerl_constr.hrl:52: Warning: record node_anchor has field(s) without type information

/home/fra/elixir-omg/deps/yamerl/include/internal/yamerl_constr.hrl:45: Warning: record unfinished_node has field(s) without type information
/home/fra/elixir-omg/deps/yamerl/include/internal/yamerl_constr.hrl:52: Warning: record node_anchor has field(s) without type information
include/internal/yamerl_constr.hrl:45: Warning: record unfinished_node has field(s) without type information
include/internal/yamerl_constr.hrl:52: Warning: record node_anchor has field(s) without type information

/home/fra/elixir-omg/deps/yamerl/include/internal/yamerl_constr.hrl:45: Warning: record unfinished_node has field(s) without type information
/home/fra/elixir-omg/deps/yamerl/include/internal/yamerl_constr.hrl:52: Warning: record node_anchor has field(s) without type information
include/internal/yamerl_constr.hrl:45: Warning: record unfinished_node has field(s) without type information
include/internal/yamerl_constr.hrl:52: Warning: record node_anchor has field(s) without type information

/home/fra/elixir-omg/deps/yamerl/include/internal/yamerl_constr.hrl:45: Warning: record unfinished_node has field(s) without type information
/home/fra/elixir-omg/deps/yamerl/include/internal/yamerl_constr.hrl:52: Warning: record node_anchor has field(s) without type information
include/internal/yamerl_constr.hrl:45: Warning: record unfinished_node has field(s) without type information
include/internal/yamerl_constr.hrl:52: Warning: record node_anchor has field(s) without type information

/home/fra/elixir-omg/deps/yamerl/include/internal/yamerl_constr.hrl:45: Warning: record unfinished_node has field(s) without type information
/home/fra/elixir-omg/deps/yamerl/include/internal/yamerl_constr.hrl:52: Warning: record node_anchor has field(s) without type information
include/internal/yamerl_constr.hrl:45: Warning: record unfinished_node has field(s) without type information
include/internal/yamerl_constr.hrl:52: Warning: record node_anchor has field(s) without type information

/home/fra/elixir-omg/deps/yamerl/include/internal/yamerl_constr.hrl:45: Warning: record unfinished_node has field(s) without type information
/home/fra/elixir-omg/deps/yamerl/include/internal/yamerl_constr.hrl:52: Warning: record node_anchor has field(s) without type information
include/internal/yamerl_constr.hrl:45: Warning: record unfinished_node has field(s) without type information
include/internal/yamerl_constr.hrl:52: Warning: record node_anchor has field(s) without type information

/home/fra/elixir-omg/deps/yamerl/include/internal/yamerl_constr.hrl:45: Warning: record unfinished_node has field(s) without type information
/home/fra/elixir-omg/deps/yamerl/include/internal/yamerl_constr.hrl:52: Warning: record node_anchor has field(s) without type information
include/internal/yamerl_constr.hrl:45: Warning: record unfinished_node has field(s) without type information
include/internal/yamerl_constr.hrl:52: Warning: record node_anchor has field(s) without type information

/home/fra/elixir-omg/deps/yamerl/include/internal/yamerl_constr.hrl:45: Warning: record unfinished_node has field(s) without type information
/home/fra/elixir-omg/deps/yamerl/include/internal/yamerl_constr.hrl:52: Warning: record node_anchor has field(s) without type information
include/internal/yamerl_constr.hrl:45: Warning: record unfinished_node has field(s) without type information
include/internal/yamerl_constr.hrl:52: Warning: record node_anchor has field(s) without type information

==> connection
Compiling 1 file (.ex)
Generated connection app
==> decorator
Compiling 2 files (.ex)
Generated decorator app
===> Compiling rocksdb
+ mkdir -p _build/cmake
+ cd _build/cmake
+ type cmake3
+ CMAKE=cmake
+ cmake -DWITH_SYSTEM_ROCKSDB=ON ../../c_src
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found RocksDB: /usr/lib/librocksdb.so (found suitable version "6.2.2", minimum required is "5.17.2")
-- Using OTP lib: /usr/lib/erlang/lib - found
-- Using erl_interface version: erl_interface-4.0
-- Using erts version: erts-11.0.3
-- Performing Test HAVE_OMIT_LEAF_FRAME_POINTER
-- Performing Test HAVE_OMIT_LEAF_FRAME_POINTER - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/fra/elixir-omg/deps/rocksdb/_build/cmake
+ echo done.
done.
+ cd _build/cmake
+ type cmake3
+ CMAKE=cmake
+ getconf _NPROCESSORS_ONLN
+ CORES=1
+ [ x1 = x ]
+ PAR=-- -j 1
+ cmake --build . -- -j 1
Scanning dependencies of target erocksdb
[  5%] Building CXX object CMakeFiles/erocksdb.dir/erocksdb.cc.o
[ 10%] Building CXX object CMakeFiles/erocksdb.dir/backup.cc.o
[ 15%] Building CXX object CMakeFiles/erocksdb.dir/batch.cc.o
[ 20%] Building CXX object CMakeFiles/erocksdb.dir/transaction.cc.o
[ 25%] Building CXX object CMakeFiles/erocksdb.dir/bitset_merge_operator.cc.o
[ 30%] Building CXX object CMakeFiles/erocksdb.dir/cache.cc.o
/home/fra/elixir-omg/deps/rocksdb/c_src/cache.cc: In constructor â��erocksdb::Cache::Cache(std::shared_ptr<rocksdb::Cache>)â��:
/home/fra/elixir-omg/deps/rocksdb/c_src/cache.cc:69:51: warning: declaration of â��Cacheâ�� shadows a member of â��erocksdb::Cacheâ�� [-Wshadow]
 Cache::Cache(std::shared_ptr<rocksdb::Cache> Cache) : cache_(Cache) {}
                                                   ^
In file included from /home/fra/elixir-omg/deps/rocksdb/c_src/cache.cc:21:0:
/home/fra/elixir-omg/deps/rocksdb/c_src/cache.h:29:15: note: shadowed declaration is here
   class Cache {
               ^
[ 35%] Building CXX object CMakeFiles/erocksdb.dir/counter_merge_operator.cc.o
[ 40%] Building CXX object CMakeFiles/erocksdb.dir/env.cc.o
[ 45%] Building CXX object CMakeFiles/erocksdb.dir/erlang_merge.cc.o
[ 50%] Building CXX object CMakeFiles/erocksdb.dir/erocksdb_column_family.cc.o
[ 55%] Building CXX object CMakeFiles/erocksdb.dir/erocksdb_db.cc.o
[ 60%] Building CXX object CMakeFiles/erocksdb.dir/erocksdb_iter.cc.o
[ 65%] Building CXX object CMakeFiles/erocksdb.dir/erocksdb_snapshot.cc.o
[ 70%] Building CXX object CMakeFiles/erocksdb.dir/rate_limiter.cc.o
/home/fra/elixir-omg/deps/rocksdb/c_src/rate_limiter.cc: In constructor â��erocksdb::RateLimiter::RateLimiter(std::shared_ptr<rocksdb::RateLimiter>)â��:
/home/fra/elixir-omg/deps/rocksdb/c_src/rate_limiter.cc:64:75: warning: declaration of â��RateLimiterâ�� shadows a member of â��erocksdb::RateLimiterâ�� [-Wshadow]
 RateLimiter::RateLimiter(std::shared_ptr<rocksdb::RateLimiter> RateLimiter) : rate_limiter_(RateLimiter) {}
                                                                           ^
In file included from /home/fra/elixir-omg/deps/rocksdb/c_src/rate_limiter.cc:18:0:
/home/fra/elixir-omg/deps/rocksdb/c_src/rate_limiter.h:34:21: note: shadowed declaration is here
   class RateLimiter {
                     ^
[ 75%] Building CXX object CMakeFiles/erocksdb.dir/refobjects.cc.o
[ 80%] Building CXX object CMakeFiles/erocksdb.dir/sst_file_manager.cc.o
[ 85%] Building CXX object CMakeFiles/erocksdb.dir/transaction_log.cc.o
[ 90%] Building CXX object CMakeFiles/erocksdb.dir/util.cc.o
[ 95%] Building CXX object CMakeFiles/erocksdb.dir/write_buffer_manager.cc.o
make[2]: ***  Nessuna regola per generare l'obiettivo "/usr/lib/liberl_interface.a", necessario per "/home/fra/elixir-omg/deps/rocksdb/priv/liberocksdb.so".  Arresto.
CMakeFiles/Makefile2:67: set di istruzioni per l'obiettivo "CMakeFiles/erocksdb.dir/all" non riuscito
make[1]: *** [CMakeFiles/erocksdb.dir/all] Errore 2
Makefile:83: set di istruzioni per l'obiettivo "all" non riuscito
make: *** [all] Errore 2
+ exit 1
===> Hook for compile failed!

** (Mix) Could not compile dependency :rocksdb, "/home/fra/.mix/rebar3 bare compile --paths="/home/fra/elixir-omg/_build/dev/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile rocksdb", update it with "mix deps.update rocksdb" or clean it with "mix deps.clean rocksdb"

**Comment by InoMurko** [comment]
did you run `bin/setup` ?

**Comment by otherNet** [comment]
yes I did it.
I do it again ...I'll send you Output.

**Comment by otherNet** [comment]
[setup_o.txt](https://github.com/omgnetwork/elixir-omg/files/5187537/setup_o.txt)

got obvious error at user creation because already exist:

Same error as before if mix compile:

fra@server1604:~/elixir-omg$ mix compile
===> Compiling rocksdb
+ mkdir -p _build/cmake
+ cd _build/cmake
+ type cmake3
+ CMAKE=cmake
+ cmake -DWITH_SYSTEM_ROCKSDB=ON ../../c_src
-- Using OTP lib: /usr/lib/erlang/lib - found
-- Using erl_interface version: erl_interface-4.0
-- Using erts version: erts-11.0.3
-- Configuring done
-- Generating done
-- Build files have been written to: /home/fra/elixir-omg/deps/rocksdb/_build/cmake
+ echo done.
done.
+ cd _build/cmake
+ type cmake3
+ CMAKE=cmake
+ getconf _NPROCESSORS_ONLN
+ CORES=1
+ [ x1 = x ]
+ PAR=-- -j 1
+ cmake --build . -- -j 1
make[2]: ***  Nessuna regola per generare l'obiettivo "/usr/lib/liberl_interface.a", necessario per "/home/fra/elixir-omg/deps/rocksdb/priv/liberocksdb.so".  Arresto.
CMakeFiles/Makefile2:67: set di istruzioni per l'obiettivo "CMakeFiles/erocksdb.dir/all" non riuscito
make[1]: *** [CMakeFiles/erocksdb.dir/all] Errore 2
Makefile:83: set di istruzioni per l'obiettivo "all" non riuscito
make: *** [all] Errore 2
+ exit 1
===> Hook for compile failed!

** (Mix) Could not compile dependency :rocksdb, "/home/fra/.mix/rebar3 bare compile --paths="/home/fra/elixir-omg/_build/dev/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile rocksdb", update it with "mix deps.update rocksdb" or clean it with "mix deps.clean rocksdb"
fra@server1604:~/elixir-omg$

**Comment by unnawut** [comment]
I might be guessing wrongly but it seems `Nessuna regola per generare l'obiettivo "/usr/lib/liberl_interface.a", necessario per "/home/fra/elixir-omg/deps/rocksdb/priv/liberocksdb.so". Arresto.` could be because of your erlang version.

Could you try install erlang 22.3 instead? This is the versions we use: https://github.com/omgnetwork/elixir-omg/blob/master/.tool-versions

**Comment by InoMurko** [comment]
No activity.

**Comment by muhammad-waheed-2558** [comment]
Hey, I'm also getting the cmake issue. Please guide me
+ mkdir -p _build/cmake
+ cd _build/cmake
+ type cmake3
+ CMAKE=cmake
+ cmake ../../c_src
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- cmake args -DCMAKE_POSITION_INDEPENDENT_CODE=ON;-DCMAKE_CXX_COMPILER=/usr/bin/g++;-DCMAKE_AR=/usr/bin/ar;-DCMAKE_BUILD_TYPE=Release;-DFAIL_ON_WARNINGS=OFF;-DPORTABLE=ON;-DUSE_RTTI=1;-DWITH_TOOLS=OFF;-DWITH_TESTS=OFF;-DWITH_GFLAGS=OFF;-DWITH_JEMALLOC=OFF;-DWITH_TBB=;-DWITH_SNAPPY=;-DWITH_LZ4=;-DWITH_ZLIB=;-DWITH_BZ2=;-DWITH_ZSTD=
-- Found RocksDB library: /home/ubuntu/projects/jetzy/deps/rocksdb/_build/cmake/rocksdb-prefix/src/rocksdb-build/librocksdb.a
-- Found RocksDB includes: /home/ubuntu/projects/jetzy/deps/rocksdb/c_src/../deps/rocksdb/include
-- Using OTP lib: /home/ubuntu/.asdf/installs/erlang/25.3.2.2/lib - found
-- Using erl_interface version: erl_interface-5.3.2
-- Using erts version: erts-13.2.2.1
-- Configuring done (0.7s)
-- Generating done (0.0s)
-- Build files have been written to: /home/ubuntu/projects/jetzy/deps/rocksdb/_build/cmake
+ echo done.
done.
===> Analyzing applications...
===> Compiling rocksdb
+ cd _build/cmake
+ type cmake3
+ CMAKE=cmake
+ getconf _NPROCESSORS_ONLN
+ CORES=12
+ [ x12 = x ]
+ PAR=-- -j 12
+ cmake --build . -- -j 12
[  3%] Performing build step for 'rocksdb'
[  0%] Building CXX object CMakeFiles/rocksdb.dir/table/block_based/hash_index_reader.cc.o
[  0%] Building CXX object CMakeFiles/rocksdb.dir/table/block_based/data_block_hash_index.cc.o
[  0%] Building CXX object CMakeFiles/rocksdb.dir/table/block_based/index_builder.cc.o
[  0%] Building CXX object CMakeFiles/rocksdb.dir/table/block_based/index_reader_common.cc.o
[  0%] Building CXX object CMakeFiles/rocksdb.dir/table/block_based/parsed_full_filter_block.cc.o
[  0%] Building CXX object CMakeFiles/rocksdb.dir/table/block_based/partitioned_filter_block.cc.o
[  0%] Building CXX object CMakeFiles/rocksdb.dir/table/block_based/partitioned_index_reader.cc.o
[  2%] Building CXX object CMakeFiles/rocksdb.dir/table/block_fetcher.cc.o
[  2%] Building CXX object CMakeFiles/rocksdb.dir/table/block_based/partitioned_index_iterator.cc.o
[  2%] Building CXX object CMakeFiles/rocksdb.dir/table/block_based/reader_common.cc.o
[  2%] Building CXX object CMakeFiles/rocksdb.dir/table/cuckoo/cuckoo_table_builder.cc.o
[  2%] Building CXX object CMakeFiles/rocksdb.dir/table/block_based/uncompression_dict_reader.cc.o
In file included from /home/ubuntu/projects/jetzy/deps/rocksdb/deps/rocksdb/table/block_based/data_block_hash_index.cc:9:
/home/ubuntu/projects/jetzy/deps/rocksdb/deps/rocksdb/table/block_based/data_block_hash_index.h:65:7: error: ‘uint8_t’ does not name a type
   65 | const uint8_t kNoEntry = 255;
      |       ^~~~~~~
/home/ubuntu/projects/jetzy/deps/rocksdb/deps/rocksdb/table/block_based/data_block_hash_index.h:1:1: note: ‘uint8_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
  +++ |+#include <cstdint>
    1 | // Copyright (c) 2011-present, Facebook, Inc. All rights reserved.
/home/ubuntu/projects/jetzy/deps/rocksdb/deps/rocksdb/table/block_based/data_block_hash_index.h:66:7: error: ‘uint8_t’ does not name a type
   66 | const uint8_t kCollision = 254;
